language: python
sudo: false
matrix:
  include:
  - python: 2.7
  - python: 3.5
  - python: 3.6
  - python: 3.7
    dist: xenial
    sudo: true
  - python: nightly
  - python: pypy3
  allow_failures:
  - python: nightly
before_install:
- pip install codecov
- pip install 'py>=1.5.0'
install:
- pip install -r requirements.txt
- pip install -r requirements_dev.txt
- pip install -e .
script:
- python setup.py
after_success:
- codecov
deploy:
  provider: pypi
  user: ShagaleevAlexey
  password:
    secure: PRdxnCoLCjpZkzmsgOF4Yiq3HdbXe2Sq/tv2agyFXOVRzPE78rqrqPOqJIZOLvSoXimvxhRa50b+sBRCYTyZSap3i68ufDyC3q7fJsr2npF60n8GbeANN7TH2zuIqzalPn/Sy7jH7hlZ7KGhdJPk3IaqkhAozfZz+Acn1XyzJazUraunwkwCNYc72guc6KlEOB5foTgqPthWlDvIvsDxjOz+Rb0jmGki+nOb/mHKXK2bcpOYWyeqqH2QsGHw66L0iiBZ3Ozeaf8CTvtVVb1HWE3MRknwXgxMM5VcA0lwx3cSouCx9xq5xjukfTz5O+l/fcJoh2nU5aWIbHZK+kVQLFvG66MeuOZh3JTPz1dsCKvp++Un7pXHL0CR6aaBAJyugNWcB+bJba4lmNjgYvun5nTCN4caB5SksW7Cn6MT4Oub1vxqmOZf4bPgQtoKppagfyG7tXRloU5SVEjKQiO4P2j+f/q5/nlpazrNmAg1Gb6edMifVlMv5I1MxrlcPfQA2F8fqPQoISdttlDvRtF3W4ZtaLXVRfJ3Js0u4+IbFeS5o8dfsrffPI+Ocj6JTRdU0qvrOkU7Ev216Zouaa1ELqyUlDmedlA2HgEtLpZtbGWx/ExHRpiyyNpIZ4E8X8bVc5Pr8I8+yMU82Rgg73yUaM0sMv9hm/2J61k3UMatrdU=
  distributions: sdist bdist_wheel
  on:
    tags: true
